lekiwi:
  controller_manager:
    ros__parameters:
      update_rate: 10  # Hz
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      arm_position_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      gripper_position_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      wheel_velocity_controller:
        type: forward_command_controller/ForwardCommandController

  arm_position_controller:
    ros__parameters:
      joints:
        - STS3215_03a_v1_Revolute_45
        - STS3215_03a_v1_1_Revolute_49
        - STS3215_03a_v1_2_Revolute_51
        - STS3215_03a_v1_3_Revolute_53
        - STS3215_03a_Wrist_Roll_v1_Revolute_55
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_partial_joints_goal: true
      constraints:
        goal_time: 0.5
        stopped_velocity_tolerance: 0.05
        STS3215_03a_v1_Revolute_45:
          trajectory: 0.2
          goal: 0.05
        STS3215_03a_v1_1_Revolute_49:
          trajectory: 0.2
          goal: 0.05
        STS3215_03a_v1_2_Revolute_51:
          trajectory: 0.2
          goal: 0.05
        STS3215_03a_v1_3_Revolute_53:
          trajectory: 0.2
          goal: 0.05
        STS3215_03a_Wrist_Roll_v1_Revolute_55:
          trajectory: 0.2
          goal: 0.05

  gripper_position_controller:
    ros__parameters:
      joints:
        - STS3215_03a_v1_4_Revolute_57
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_partial_joints_goal: false
      constraints:
        goal_time: 0.5
        stopped_velocity_tolerance: 0.05
        STS3215_03a_v1_4_Revolute_57:
          trajectory: 0.2
          goal: 0.05

  wheel_velocity_controller:
    ros__parameters:
      joints:
        - joint7
        - joint8
        - joint9
      interface_name: velocity
