lekiwi:
  controller_manager:
    ros__parameters:
      update_rate: 10  # Hz
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      kiwi_controller:
        type: forward_command_controller/ForwardCommandController
      arm_position_controller:
        type: forward_command_controller/ForwardCommandController
      gripper_position_controller:
        type: forward_command_controller/ForwardCommandController

  kiwi_controller:
    ros__parameters:
      joints: [joint7, joint8, joint9]
      interface_name: velocity

  arm_position_controller:
    ros__parameters:
      joints:
        - STS3215_03a_v1_Revolute_45
        - STS3215_03a_v1_1_Revolute_49
        - STS3215_03a_v1_2_Revolute_51
        - STS3215_03a_v1_3_Revolute_53
        - STS3215_03a_Wrist_Roll_v1_Revolute_55
      interface_name: position

  gripper_position_controller:
    ros__parameters:
      joints:
        - STS3215_03a_v1_4_Revolute_57
      interface_name: position
